// The critical CSS is inlined in index.html, allowed by a CSP hash. Added 2026-09-17.
//
// It used to be a blocking <link> to /css/hero.css, which PageSpeed then flagged as the page's only
// render-blocking request (est. 170ms, and one extra round trip before the first paint on every
// cold visit). index.html carried a comment saying an inline <style> was impossible because
// _headers pins style-src to 'self' with no 'unsafe-inline' -- true of 'unsafe-inline', but a
// 'sha256-...' source allows exactly one known block of bytes and nothing else, which is stricter
// than loading a whole stylesheet by URL.
//
// The failure mode is what these tests exist for: if the hash and the block ever drift apart, the
// browser refuses to apply the style and the hero paints unstyled -- the 229px collapse from
// test/header-first-paint.test.js, back again. So the hash is generated by the build, never typed,
// and recomputed from the two files here on every test run.
//
// Run with: npm test

const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { buildHeroCss } = require('../scripts/build-hero-css');

const WWWROOT = path.join(__dirname, '..', 'wwwroot');
const INDEX = fs.readFileSync(path.join(WWWROOT, 'index.html'), 'utf8');
const HEADERS = fs.readFileSync(path.join(WWWROOT, '_headers'), 'utf8');
const STYLE_CSS = fs.readFileSync(path.join(WWWROOT, 'css', 'style.css'), 'utf8');

// The exact text content of the inlined block -- which is what the CSP hash covers.
function inlineCriticalCss() {
  const m = INDEX.match(/<!-- BEGIN-CRITICAL-CSS[^>]*-->\s*<style>([\s\S]*?)<\/style>/);
  assert.ok(m, 'index.html should carry the generated critical CSS between its BEGIN/END markers');
  return m[1];
}
function sha256Base64(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('base64');
}
// The site-wide CSP (the `/*` rule). The embed widget has its own, further down the file.
function siteWideCsp() {
  const lines = HEADERS.split(/\r?\n/).filter((l) => l.includes('Content-Security-Policy:'));
  assert.ok(lines.length >= 1, '_headers should still set a CSP');
  return lines[0];
}

test('the critical CSS is inline, not a blocking request', () => {
  assert.ok(!/<link rel="stylesheet" href="\/css\/hero\.css/.test(INDEX),
    'the blocking <link> was the only render-blocking request on the page');
  assert.ok(inlineCriticalCss().length > 5000, 'and the real rules are in the document');
});

test('the inlined block is exactly what the generator produces', () => {
  assert.equal(inlineCriticalCss(), buildHeroCss(STYLE_CSS).trim(),
    'run `npm run build` -- the inlined critical CSS is stale');
});

test('it is one line, so a line-ending conversion cannot invalidate the hash', () => {
  // The single most likely way for this to break: git normalising CRLF inside the block on
  // checkout, changing the bytes the browser hashes. Minified output has no newlines; keep it that
  // way and there is nothing for a conversion to touch.
  assert.ok(!inlineCriticalCss().includes('\n'), 'the block must stay on one line');
  assert.match(INDEX, /-->\s*<style>@/, 'and start immediately, with no whitespace inside the tag');
});

test('the CSP allows that exact block, by hash', () => {
  const csp = siteWideCsp();
  const expected = "'sha256-" + sha256Base64(inlineCriticalCss()) + "'";
  assert.ok(csp.includes(expected), 'style-src should carry ' + expected + '\ngot: ' + (csp.match(/style-src[^;]*/) || [''])[0]);
});

test('and nothing more than that block', () => {
  const styleSrc = (siteWideCsp().match(/style-src([^;]*)/) || ['', ''])[1];
  assert.ok(!styleSrc.includes('unsafe-inline'), "'unsafe-inline' would allow any inline style on the site");
  assert.ok(!styleSrc.includes('unsafe-eval'), 'nor unsafe-eval');
  assert.ok(styleSrc.includes("'self'"), "style.min.css still loads by URL, so 'self' stays");
  const hashes = styleSrc.match(/'sha256-[^']+'/g) || [];
  assert.equal(hashes.length, 1, 'exactly one hash -- a leftover from an old build would be a standing allowance: ' + hashes.join(' '));
});

test('the embed widget CSP is untouched', () => {
  // wwwroot/embed/qotd/ is iframed on third-party sites and has its own scoped CSP, whose comment
  // says its script and style are external files specifically so it never needs an inline source.
  const scoped = HEADERS.split(/\r?\n/).filter((l) => l.includes('Content-Security-Policy:'))[1];
  assert.ok(scoped, 'the scoped CSP for /embed/qotd/ should still be there');
  assert.ok(!scoped.includes('sha256-'), 'the widget does not inline anything');
});

// Track pages (/cdl/tx etc.) get no server-rendered hero, so no app-ssr-reserve: #app arrives empty, the
// footer painted at y~540 and was then shoved off-screen when renderTrackLanding filled the page. Measured
// 2026-09-19 on /cdl/tx: CLS 0.41-0.89 desktop, 1.38-1.47 on a throttled phone; 0.04-0.07 and 0.013-0.017
// with this rule. It has to be in the inlined block, since style.min.css attaches too late to help.
test('an empty #app reserves one viewport at first paint', () => {
  assert.match(STYLE_CSS, /#app:empty\s*\{\s*min-height:\s*100vh;?\s*\}/, 'the rule lives in style.css');
  assert.ok(inlineCriticalCss().includes('#app:empty{min-height:100vh}'), 'and is in the inlined critical CSS');
});

test('hero.css is still generated, for the tests that read it', () => {
  // Nothing links to it any more, but it is the artefact the header/hero first-paint tests assert
  // against and the input to the hash, so the build still writes it.
  assert.ok(fs.existsSync(path.join(WWWROOT, 'css', 'hero.css')));
});
